version: '3.8'
services:
  backend:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: ["python", "run_pipeline.py"]

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-newsuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-newspass}
      POSTGRES_DB: ${POSTGRES_DB:-newsdb}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: 